### ISSUE TITLE
setup-env script should allow one to specify Python version

### ISSUE THREAD

**Issue by jsf9k** [cisagov/skeleton-generic#153]
# 💡 Summary #

The `setup-env` script should allow one to specify the version of Python to use for the virtual environment.

## Motivation and context ##

The `setup-env` script currently creates the Python virtual environment without specifying a Python version via the command `pyenv virtualenv <venv_name>`.  Because no Python version is specified, `pyenv` uses the system Python.  I personally prefer to use the latest version of Python I have installed via `pyenv`, which is usually several patch versions ahead.

## Implementation notes ##

I'm fine with the default behavior remaining the default, but I'd like to also be able to either (or both!):
- Specify the Python version to use directly as a CLI option.  There should be a check to verify that the Python version specified is actually available.
- Have a different CLI option that leverages `pyenv versions` to list the available Python versions and then allow me to select one interactively.

The first option is obviously easier to implement.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Users can specify the Python version to use when sunning `setup-env`.

**Comment by michaelsaki** [comment]
When we have a user specify the Python version from `pyenv versions` do we want them to be able to only specify Python versions (e.g. 3.9.6) or if they have a virtual environment (e.g. `venv`) in the output of `pyenv versions` do we want them to be able to choose that virtual environment?

**Comment by mcdonnnj** [comment]
> When we have a user specify the Python version from `pyenv versions` do we want them to be able to only specify Python versions (e.g. 3.9.6) or if they have a virtual environment (e.g. `venv`) in the output of `pyenv versions` do we want them to be able to choose that virtual environment?

My opinion is that a given virtual environment should be exclusive to a project in this context. That is the only way to isolate `pip` environments correctly.
