### ISSUE TITLE
`setup-env` should check that Python version is a valid semantic version

### ISSUE THREAD

**Issue by jsf9k** [cisagov/skeleton-generic#167]
# 💡 Summary #

When the user specifies a Python version via `-v` or `--version`, `setup-env` should verify that the specified version is a valid semantic version.

## Motivation and context ##

Python uses semantic versioning, so it makes sense to perform this additional check.

## Implementation notes ##

One of [these regexes](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) should do the trick.

**Comment by michaelsaki** [comment]
@jsf9k I have the fix for this here https://github.com/cisagov/skeleton-generic/tree/improvement/correct-semantic-python-version-checks. I am waiting for PR: https://github.com/cisagov/skeleton-generic/pull/166 to get approved and merged before opening the PR since it is based off of that branch.

**Comment by michaelsaki** [comment]
@cisagov/team-ois Going to open a PR for this shortly but one thing I wanted to check was how do we want the error message to look for an invalid semantic version of Python?

Right now I have it set to `Error: The specified Python version: {invalid_sematic_version}, does not follow the semantic versioning standard.`

Are we ok with this? I was also considering providing them with an example of a valid semantic version but wasn't sure if that might be overkill.

**Comment by jsf9k** [comment]
Just state that it is an invalid version of Python.  Python follows semantic versioning, so any version string that is not a valid semantic version is an invalid version of Python.
