### ISSUE TITLE
All GitHub Actions `lint` Workflows Should Use cisagov/setup-env-github-action

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/skeleton-generic#74]
# 🐛 Summary #

The version of [Terraform](https://www.terraform.io/) that is installed in [GitHub Actions virtual environments](https://github.com/actions/virtual-environments) is `0.15.3` (at time of typing). However, we use `0.12.31` in development, and [cisagov/setup-env-github-action](https://github.com/cisagov/setup-env-github-action) currently installs `0.12.30`.

If a project does not descend from [cisagov/skeleton-packer](https://github.com/cisagov/skeleton-packer) or [cisagov/skeleton-tf-module](https://github.com/cisagov/skeleton-tf-module) it will not use [cisagov/setup-env-github-action](https://github.com/cisagov/setup-env-github-action) to enforce our in-use Terraform version. However, we have a `terraform_fmt` hook configured for [pre-commit](https://pre-commit.com/) which will run on any Terraform files in the repository. This will result in differing behavior between local and GHA linting checks if a project happens to include Terraform code without descending from the aforementioned skeleton repositories.

## To reproduce ##

Descend from [cisagov/skeleton-generic](https://github.com/cisagov/skeleton-generic) and include Terraform code.

## Expected behavior ##

If you pass `pre-commit` checks locally, you should pass them once changes are pushed to GitHub.

## Any helpful log output or screenshots ##

You can see a sample of a failed GHA run at https://github.com/cisagov/orchestrator/runs/2617296185?check_suite_focus=true and the commit that results from manually running `terraform fmt` with Terraform 0.15.3 against the `terraform/` directory in that repository at https://github.com/cisagov/orchestrator/commit/212a26ac35f7836b47cb934fa0e9095abeb684c8 with passing actions at https://github.com/cisagov/orchestrator/actions/runs/855866514

**Comment by jsf9k** [comment]
The same thing goes for the Packer hooks.
